In [1]:
import pandas as pd
import os

In [2]:
path = r"C:\Users\VAIBHAV\Downloads\archive (5)"

all_data = []

for file in os.listdir(path):
    if file.endswith(".csv"):
        if file == 'stock_metadata.csv':
            continue
        file_path = os.path.join(path, file)

        df = pd.read_csv(file_path)
        
        symbol = file.replace(".csv", "")
        df['Firm'] = symbol
        
        all_data.append(df)

In [3]:
df = pd.concat(all_data, ignore_index=True)
df.head(50)

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_17880\273962504.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(all_data, ignore_index=True)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Firm
0,2007-11-27,MUNDRAPORT,EQ,440.00,770.00,1050.00,770.00,959.00,962.90,984.72,27294366,2.687719e+15,NaN,9859619.0,0.3612,ADANIPORTS
1,2007-11-28,MUNDRAPORT,EQ,962.90,984.00,990.00,874.00,885.00,893.90,941.38,4581338,4.312765e+14,NaN,1453278.0,0.3172,ADANIPORTS
2,2007-11-29,MUNDRAPORT,EQ,893.90,909.00,914.75,841.00,887.00,884.20,888.09,5124121,4.550658e+14,NaN,1069678.0,0.2088,ADANIPORTS
3,2007-11-30,MUNDRAPORT,EQ,884.20,890.00,958.00,890.00,929.00,921.55,929.17,4609762,4.283257e+14,NaN,1260913.0,0.2735,ADANIPORTS
4,2007-12-03,MUNDRAPORT,EQ,921.55,939.75,995.00,922.00,980.00,969.30,965.65,2977470,2.875200e+14,NaN,816123.0,0.2741,ADANIPORTS
5,2007-12-04,MUNDRAPORT,EQ,969.30,985.00,1056.00,976.00,1049.00,1041.45,1015.39,4849250,4.923867e+14,NaN,1537667.0,0.3171,ADANIPORTS
6,2007-12-05,MUNDRAPORT,EQ,1041.45,1061.00,1099.50,1050.00,1084.00,1082.45,1082.79,2848209,3.084010e+14,NaN,904260.0,0.3175,ADANIPORTS
7,2007-12-06,MUNDRAPORT,EQ,1082.45,1089.00,1109.70,1051.00,1090.10,1081.30,1087.03,1749516,1.901771e+14,NaN,825691.0,0.4720,ADANIPORTS
8,2007-12-07,MUNDRAPORT,EQ,1081.30,1100.00,1134.00,1078.00,1100.00,1102.40,1106.57,2247904,2.487465e+14,NaN,697763.0,0.3104,ADANIPORTS
9,2007-12-10,MUNDRAPORT,EQ,1102.40,1110.00,1110.00,1061.10,1073.55,1075.40,1080.38,1012350,1.093727e+14,NaN,417514.0,0.4124,ADANIPORTS
10,2007-12-11,MUNDRAPORT,EQ,1075.40,1081.00,1089.00,1041.00,1046.00,1047.65,1067.80,810464,8.654156e+13,NaN,415191.0,0.5123,ADANIPORTS
11,2007-12-12,MUNDRAPORT,EQ,1047.65,1032.00,1065.00,1016.00,1036.90,1036.80,1043.92,744799,7.775137e+13,NaN,363848.0,0.4885,ADANIPORTS
12,2007-12-13,MUNDRAPORT,EQ,1036.80,1040.00,1150.00,1030.25,1131.15,1129.95,1109.09,3067687,3.402339e+14,NaN,1040076.0,0.3390,ADANIPORTS
13,2007-12-14,MUNDRAPORT,EQ,1129.95,1139.90,1140.00,1101.10,1107.00,1110.50,1119.55,1070737,1.198746e+14,NaN,525239.0,0.4905,ADANIPORTS
14,2007-12-17,MUNDRAPORT,EQ,1110.50,1140.00,1168.00,1021.50,1052.00,1044.25,1102.42,1404955,1.548848e+14,NaN,670298.0,0.4771,ADANIPORTS
15,2007-12-18,MUNDRAPORT,EQ,1044.25,1045.00,1109.90,1031.55,1085.00,1074.95,1077.84,1226984,1.322495e+14,NaN,449420.0,0.3663,ADANIPORTS
16,2007-12-19,MUNDRAPORT,EQ,1074.95,1091.00,1116.00,1046.30,1078.00,1066.90,1082.93,845666,9.157976e+13,NaN,344171.0,0.4070,ADANIPORTS
17,2007-12-20,MUNDRAPORT,EQ,1066.90,1083.50,1083.50,1051.00,1067.00,1060.20,1065.52,623288,6.641271e+13,NaN,276356.0,0.4434,ADANIPORTS
18,2007-12-24,MUNDRAPORT,EQ,1060.20,1095.00,1192.00,1085.25,1160.00,1156.80,1160.77,2060892,2.392214e+14,NaN,807879.0,0.3920,ADANIPORTS
19,2007-12-26,MUNDRAPORT,EQ,1156.80,1175.00,1214.00,1148.00,1212.00,1199.90,1183.30,1467031,1.735939e+14,NaN,469389.0,0.3200,ADANIPORTS
20,2007-12-27,MUNDRAPORT,EQ,1199.90,1215.00,1240.00,1204.00,1209.00,1211.65,1222.58,977495,1.195065e+14,NaN,355431.0,0.3636,ADANIPORTS
21,2007-12-28,MUNDRAPORT,EQ,1211.65,1189.40,1274.00,1175.00,1270.00,1249.10,1221.31,1164138,1.421773e+14,NaN,503564.0,0.4326,ADANIPORTS
22,2007-12-31,MUNDRAPORT,EQ,1249.10,1263.35,1295.00,1261.00,1268.00,1268.80,1277.64,737249,9.419421e+13,NaN,316377.0,0.4291,ADANIPORTS
23,2008-01-01,MUNDRAPORT,EQ,1268.80,1279.00,1319.00,1263.70,1308.00,1296.85,1285.72,491348,6.317346e+13,NaN,172911.0,0.3519,ADANIPORTS
24,2008-01-02,MUNDRAPORT,EQ,1296.85,1310.25,1324.00,1270.00,1300.15,1307.45,1302.15,703815,9.164734e+13,NaN,221397.0,0.3146,ADANIPORTS
25,2008-01-03,MUNDRAPORT,EQ,1307.45,1305.00,1314.70,1261.15,1267.15,1275.80,1289.24,505058,6.511425e+13,NaN,217437.0,0.4305,ADANIPORTS
26,2008-01-04,MUNDRAPORT,EQ,1275.80,1278.80,1294.80,1233.00,1239.90,1240.35,1256.03,550795,6.918167e+13,NaN,230237.0,0.4180,ADANIPORTS
27,2008-01-07,MUNDRAPORT,EQ,1240.35,1240.00,1278.90,1215.00,1233.00,1227.25,1244.76,630963,7.853977e+13,NaN,239404.0,0.3794,ADANIPORTS
28,2008-01-08,MUNDRAPORT,EQ,1227.25,1240.00,1255.00,1185.00,1202.00,1204.80,1217.08,530499,6.456595e+13,NaN,228866.0,0.4314,ADANIPORTS
29,2008-01-09,MUNDRAPORT,EQ,1204.80,1200.00,1210.00,1151.00,1181.00,1180.25,1176.37,627507,7.381831e+13,NaN,259280.0,0.4132,ADANIPORTS
30,2008-01-10,MUNDRAPORT,EQ,1180.25,1185.00,1199.80,1110.00,1118.00,1121.55,1156.44,438806,5.074525e+13,NaN,200150.0,0.4561,ADANIPORTS
31,2008-01-11,MUNDRAPORT,EQ,1121.55,1128.00,1130.00,1063.00,1096.00,1085.85,1087.78,616938,6.710927e+13,NaN,312121.0,0.5059,ADANIPORTS
32,2008-01-14,MUNDRAPORT,EQ,1085.85,1082.40,1082.40,1031.10,1035.00,1035.15,1042.40,835916,8.713571e+13,NaN,570824.0,0.6829,ADANIPORTS
33,2008-01-15,MUNDRAPORT,EQ,1035.15,1045.60,1078.70,1036.05,1057.00,1049.55,1050.69,830493,8.725934e+13,NaN,504259.0,0.6072,ADANIPORTS
34,2008-01-16,MUNDRAPORT,EQ,1049.55,1046.00,1064.00,1000.00,1038.30,1030.40,1032.86,816188,8.430061e+13,NaN,478517.0,0.5863,ADANIPORTS
35,2008-01-17,MUNDRAPORT,EQ,1030.40,1050.00,1053.50,1011.00,1014.95,1020.90,1033.73,336003,3.473349e+13,NaN,145194.0,0.4321,ADANIPORTS
36,2008-01-18,MUNDRAPORT,EQ,1020.90,1010.00,1072.00,974.90,995.00,994.60,1022.57,676854,6.921328e+13,NaN,278615.0,0.4116,ADANIPORTS
37,2008-01-21,MUNDRAPORT,EQ,994.60,995.00,1005.00,795.70,853.00,825.05,880.77,788623,6.945990e+13,NaN,474223.0,0.6013,ADANIPORTS
38,2008-01-22,MUNDRAPORT,EQ,825.05,700.00,810.00,660.05,739.00,735.55,703.20,546161,3.840611e+13,NaN,376194.0,0.6888,ADANIPORTS
39,2008-01-23,MUNDRAPORT,EQ,735.55,760.00,881.90,760.00,862.20,857.00,818.67,535462,4.383653e+13,NaN,283881.0,0.5302,ADANIPORTS
40,2008-01-24,MUNDRAPORT,EQ,857.00,875.00,935.00,812.00,814.70,814.15,854.83,511017,4.368332e+13,NaN,258346.0,0.5056,ADANIPORTS
41,2008-01-25,MUNDRAPORT,EQ,814.15,820.00,883.00,820.00,866.00,865.70,858.33,404045,3.468033e+13,NaN,178177.0,0.4410,ADANIPORTS
42,2008-01-28,MUNDRAPORT,EQ,865.70,835.00,835.00,783.20,822.00,820.80,804.38,467052,3.756855e+13,NaN,241365.0,0.5168,ADANIPORTS
43,2008-01-29,MUNDRAPORT,EQ,820.80,840.00,860.00,820.05,840.00,840.75,841.27,220070,1.851382e+13,NaN,74141.0,0.3369,ADANIPORTS
44,2008-01-30,MUNDRAPORT,EQ,840.75,849.80,864.00,822.25,834.00,830.45,833.82,286190,2.386311e+13,NaN,165926.0,0.5798,ADANIPORTS
45,2008-01-31,MUNDRAPORT,EQ,830.45,831.00,849.90,812.55,836.60,837.65,833.58,194300,1.619656e+13,NaN,103890.0,0.5347,ADANIPORTS
46,2008-02-01,MUNDRAPORT,EQ,837.65,831.65,852.30,820.00,826.00,825.35,828.09,204391,1.692545e+13,NaN,115715.0,0.5661,ADANIPORTS
47,2008-02-04,MUNDRAPORT,EQ,825.35,847.90,872.40,840.00,859.00,856.10,858.77,280230,2.406521e+13,NaN,128195.0,0.4575,ADANIPORTS
48,2008-02-05,MUNDRAPORT,EQ,856.10,856.00,857.00,830.00,834.65,834.30,842.06,162093,1.364919e+13,NaN,96153.0,0.5932,ADANIPORTS
49,2008-02-06,MUNDRAPORT,EQ,834.30,803.00,824.90,780.00,809.00,807.50,810.50,193260,1.566379e+13,NaN,110565.0,0.5721,ADANIPORTS

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470384 entries, 0 to 470383
Data columns (total 16 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Date                470384 non-null  object
 1   Symbol              470384 non-null  object
 2   Series              470384 non-null  object
 3   Prev Close          470384 non-null  float64
 4   Open                470384 non-null  float64
 5   High                470384 non-null  float64
 6   Low                 470384 non-null  float64
 7   Last                470384 non-null  float64
 8   Close               470384 non-null  float64
 9   VWAP                470384 non-null  float64
 10  Volume              470384 non-null  object
 11  Turnover            470384 non-null  float64
 12  Trades              240688 non-null  float64
 13  Deliverable Volume  438230 non-null  float64
 14  %Deliverble         438230 non-null  float64
 15  Firm                470384 non-null  object
dtypes: float64(11), object(5)
memory usage: 57.4+ MB

In [5]:
df['Trades']=df['Trades'].fillna(0)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470384 entries, 0 to 470383
Data columns (total 16 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Date                470384 non-null  object
 1   Symbol              470384 non-null  object
 2   Series              470384 non-null  object
 3   Prev Close          470384 non-null  float64
 4   Open                470384 non-null  float64
 5   High                470384 non-null  float64
 6   Low                 470384 non-null  float64
 7   Last                470384 non-null  float64
 8   Close               470384 non-null  float64
 9   VWAP                470384 non-null  float64
 10  Volume              470384 non-null  object
 11  Turnover            470384 non-null  float64
 12  Trades              470384 non-null  float64
 13  Deliverable Volume  438230 non-null  float64
 14  %Deliverble         438230 non-null  float64
 15  Firm                470384 non-null  object
dtypes: float64(11), object(5)
memory usage: 57.4+ MB

In [7]:
df['Date'] = pd.to_datetime(df['Date'], 
      dayfirst = True     
)
df['year']=df['Date'].dt.year
df.head()

C:\Users\VAIBHAV\AppData\Local\Temp\ipykernel_17880\3245663829.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['Date'] = pd.to_datetime(df['Date'],

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,Firm,year
0,2007-11-27,MUNDRAPORT,EQ,440.00,770.00,1050.00,770.0,959.0,962.90,984.72,27294366,2.687719e+15,0.0,9859619.0,0.3612,ADANIPORTS,2007
1,2007-11-28,MUNDRAPORT,EQ,962.90,984.00,990.00,874.0,885.0,893.90,941.38,4581338,4.312765e+14,0.0,1453278.0,0.3172,ADANIPORTS,2007
2,2007-11-29,MUNDRAPORT,EQ,893.90,909.00,914.75,841.0,887.0,884.20,888.09,5124121,4.550658e+14,0.0,1069678.0,0.2088,ADANIPORTS,2007
3,2007-11-30,MUNDRAPORT,EQ,884.20,890.00,958.00,890.0,929.0,921.55,929.17,4609762,4.283257e+14,0.0,1260913.0,0.2735,ADANIPORTS,2007
4,2007-12-03,MUNDRAPORT,EQ,921.55,939.75,995.00,922.0,980.0,969.30,965.65,2977470,2.875200e+14,0.0,816123.0,0.2741,ADANIPORTS,2007

In [8]:
col = df.pop('Firm')
df.insert(2, 'Firm', col)
df.head()

,Date,Symbol,Firm,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,year
0,2007-11-27,MUNDRAPORT,ADANIPORTS,EQ,440.00,770.00,1050.00,770.0,959.0,962.90,984.72,27294366,2.687719e+15,0.0,9859619.0,0.3612,2007
1,2007-11-28,MUNDRAPORT,ADANIPORTS,EQ,962.90,984.00,990.00,874.0,885.0,893.90,941.38,4581338,4.312765e+14,0.0,1453278.0,0.3172,2007
2,2007-11-29,MUNDRAPORT,ADANIPORTS,EQ,893.90,909.00,914.75,841.0,887.0,884.20,888.09,5124121,4.550658e+14,0.0,1069678.0,0.2088,2007
3,2007-11-30,MUNDRAPORT,ADANIPORTS,EQ,884.20,890.00,958.00,890.0,929.0,921.55,929.17,4609762,4.283257e+14,0.0,1260913.0,0.2735,2007
4,2007-12-03,MUNDRAPORT,ADANIPORTS,EQ,921.55,939.75,995.00,922.0,980.0,969.30,965.65,2977470,2.875200e+14,0.0,816123.0,0.2741,2007

In [9]:
col = df.pop('year')
df.insert(1, 'year', col)
df.head()

,Date,year,Symbol,Firm,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
0,2007-11-27,2007,MUNDRAPORT,ADANIPORTS,EQ,440.00,770.00,1050.00,770.0,959.0,962.90,984.72,27294366,2.687719e+15,0.0,9859619.0,0.3612
1,2007-11-28,2007,MUNDRAPORT,ADANIPORTS,EQ,962.90,984.00,990.00,874.0,885.0,893.90,941.38,4581338,4.312765e+14,0.0,1453278.0,0.3172
2,2007-11-29,2007,MUNDRAPORT,ADANIPORTS,EQ,893.90,909.00,914.75,841.0,887.0,884.20,888.09,5124121,4.550658e+14,0.0,1069678.0,0.2088
3,2007-11-30,2007,MUNDRAPORT,ADANIPORTS,EQ,884.20,890.00,958.00,890.0,929.0,921.55,929.17,4609762,4.283257e+14,0.0,1260913.0,0.2735
4,2007-12-03,2007,MUNDRAPORT,ADANIPORTS,EQ,921.55,939.75,995.00,922.0,980.0,969.30,965.65,2977470,2.875200e+14,0.0,816123.0,0.2741

In [10]:
df['Volume'] = pd.to_numeric(df['Volume'].astype(str).str.replace(',', ''), errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 470384 entries, 0 to 470383
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Date                470384 non-null  datetime64[ns]
 1   year                470384 non-null  int32
 2   Symbol              470384 non-null  object
 3   Firm                470384 non-null  object
 4   Series              470384 non-null  object
 5   Prev Close          470384 non-null  float64
 6   Open                470384 non-null  float64
 7   High                470384 non-null  float64
 8   Low                 470384 non-null  float64
 9   Last                470384 non-null  float64
 10  Close               470384 non-null  float64
 11  VWAP                470384 non-null  float64
 12  Volume              470384 non-null  int64
 13  Turnover            470384 non-null  float64
 14  Trades              470384 non-null  float64
 15  Deliverable Volume  438230 non-null  float64
 16  %Deliverble         438230 non-null  float64
dtypes: datetime64[ns](1), float64(11), int32(1), int64(1), object(3)
memory usage: 59.2+ MB

In [11]:
import numpy as np

In [12]:
df['daily_return'] = (df['Close']-df['Prev Close'])/df['Prev Close']
df['daily_return'] = df['daily_return'].replace(np.inf, np.nan)
df.head()

,Date,year,Symbol,Firm,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,daily_return
0,2007-11-27,2007,MUNDRAPORT,ADANIPORTS,EQ,440.00,770.00,1050.00,770.0,959.0,962.90,984.72,27294366,2.687719e+15,0.0,9859619.0,0.3612,1.188409
1,2007-11-28,2007,MUNDRAPORT,ADANIPORTS,EQ,962.90,984.00,990.00,874.0,885.0,893.90,941.38,4581338,4.312765e+14,0.0,1453278.0,0.3172,-0.071659
2,2007-11-29,2007,MUNDRAPORT,ADANIPORTS,EQ,893.90,909.00,914.75,841.0,887.0,884.20,888.09,5124121,4.550658e+14,0.0,1069678.0,0.2088,-0.010851
3,2007-11-30,2007,MUNDRAPORT,ADANIPORTS,EQ,884.20,890.00,958.00,890.0,929.0,921.55,929.17,4609762,4.283257e+14,0.0,1260913.0,0.2735,0.042242
4,2007-12-03,2007,MUNDRAPORT,ADANIPORTS,EQ,921.55,939.75,995.00,922.0,980.0,969.30,965.65,2977470,2.875200e+14,0.0,816123.0,0.2741,0.051815

In [13]:
df[df['Prev Close']==0]

,Date,year,Symbol,Firm,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,daily_return
25572,2002-02-18,2002,BHARTI,BHARTIARTL,EQ,0.0,51.9,51.9,43.5,44.7,44.35,46.0,10381190,4.775431e+13,0.0,6503775.0,0.6265,NaN
179072,2002-02-18,2002,BHARTI,NIFTY50_all,EQ,0.0,51.9,51.9,43.5,44.7,44.35,46.0,10381190,4.775431e+13,0.0,6503775.0,0.6265,NaN

In [14]:
df['volatility']=df.groupby('Firm')['daily_return'].transform('std')
df.head()

,Date,year,Symbol,Firm,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,daily_return,volatility
0,2007-11-27,2007,MUNDRAPORT,ADANIPORTS,EQ,440.00,770.00,1050.00,770.0,959.0,962.90,984.72,27294366,2.687719e+15,0.0,9859619.0,0.3612,1.188409,0.036699
1,2007-11-28,2007,MUNDRAPORT,ADANIPORTS,EQ,962.90,984.00,990.00,874.0,885.0,893.90,941.38,4581338,4.312765e+14,0.0,1453278.0,0.3172,-0.071659,0.036699
2,2007-11-29,2007,MUNDRAPORT,ADANIPORTS,EQ,893.90,909.00,914.75,841.0,887.0,884.20,888.09,5124121,4.550658e+14,0.0,1069678.0,0.2088,-0.010851,0.036699
3,2007-11-30,2007,MUNDRAPORT,ADANIPORTS,EQ,884.20,890.00,958.00,890.0,929.0,921.55,929.17,4609762,4.283257e+14,0.0,1260913.0,0.2735,0.042242,0.036699
4,2007-12-03,2007,MUNDRAPORT,ADANIPORTS,EQ,921.55,939.75,995.00,922.0,980.0,969.30,965.65,2977470,2.875200e+14,0.0,816123.0,0.2741,0.051815,0.036699

In [15]:
df=df.sort_values(by=['Firm','Date'])

In [16]:
df['MA_20'] = df.groupby('Firm')['daily_return'].transform(lambda x: x.rolling(20).mean())
df['MA_50'] = df.groupby('Firm')['daily_return'].transform(lambda x: x.rolling(50).mean())
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 470384 entries, 0 to 470383
Data columns (total 21 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Date                470384 non-null  datetime64[ns]
 1   year                470384 non-null  int32
 2   Symbol              470384 non-null  object
 3   Firm                470384 non-null  object
 4   Series              470384 non-null  object
 5   Prev Close          470384 non-null  float64
 6   Open                470384 non-null  float64
 7   High                470384 non-null  float64
 8   Low                 470384 non-null  float64
 9   Last                470384 non-null  float64
 10  Close               470384 non-null  float64
 11  VWAP                470384 non-null  float64
 12  Volume              470384 non-null  int64
 13  Turnover            470384 non-null  float64
 14  Trades              470384 non-null  float64
 15  Deliverable Volume  438230 non-null  float64
 16  %Deliverble         438230 non-null  float64
 17  daily_return        470382 non-null  float64
 18  volatility          470384 non-null  float64
 19  MA_20               469413 non-null  float64
 20  MA_50               467883 non-null  float64
dtypes: datetime64[ns](1), float64(15), int32(1), int64(1), object(3)
memory usage: 77.2+ MB

In [17]:
df['trend'] = np.where(
    df['Close'] > df['MA_50'], 'Upward',
    np.where(df['Close'] < df['MA_50'], 'Downward', 'Neutral')
)

In [18]:
df.tail()

,Date,year,Symbol,Firm,Series,Prev Close,Open,High,Low,Last,...,Volume,Turnover,Trades,Deliverable Volume,%Deliverble,daily_return,volatility,MA_20,MA_50,trend
470379,2021-04-26,2021,ZEEL,ZEEL,EQ,188.00,190.6,191.10,185.10,186.70,...,8542755,1.600451e+14,52374.0,2340188.0,0.2739,-0.008511,0.03314,-0.005901,-0.002817,Upward
470380,2021-04-27,2021,ZEEL,ZEEL,EQ,186.40,188.0,192.95,186.80,188.80,...,14247767,2.698636e+14,73673.0,5425957.0,0.3808,0.009388,0.03314,-0.003680,-0.002265,Upward
470381,2021-04-28,2021,ZEEL,ZEEL,EQ,188.15,188.8,190.60,187.10,188.95,...,8429439,1.591917e+14,44056.0,2413974.0,0.2864,0.005049,0.03314,-0.001210,-0.002303,Upward
470382,2021-04-29,2021,ZEEL,ZEEL,EQ,189.10,190.8,191.65,186.00,186.60,...,9483009,1.777471e+14,60932.0,2744472.0,0.2894,-0.013485,0.03314,-0.002866,-0.002375,Upward
470383,2021-04-30,2021,ZEEL,ZEEL,EQ,186.55,185.3,190.95,183.65,185.00,...,11435285,2.144440e+14,62607.0,3323909.0,0.2907,-0.005092,0.03314,-0.003371,-0.002235,Upward

In [19]:
df_new=df.groupby('Firm').agg({'daily_return' : ['mean'], 'volatility' : ['mean'],'trend': lambda x: (x == 'Upward').mean()})
df_new.columns

MultiIndex([('daily_return',     'mean'),
            (  'volatility',     'mean'),
            (       'trend', '<lambda>')],
           )

In [20]:
df_new.sort_values(by=[('daily_return',     'mean')],ascending=False)

            daily_return volatility     trend
                    mean       mean  <lambda>
Firm
LT              0.076309   4.900433  0.988289
UPL             0.013274   0.831078  0.988570
JSWSTEEL        0.010461   0.602408  0.987732
ULTRACEMCO      0.007031   0.389403  0.988164
NIFTY50_all     0.002566   0.670331  0.999579
BAJFINANCE      0.001562   0.030670  0.990640
SHREECEM        0.001546   0.024554  0.990171
INDUSINDBK      0.001342   0.031018  0.990171
EICHERMOT       0.001322   0.030669  0.990756
TITAN           0.001220   0.031508  0.990765
AXISBANK        0.001193   0.030558  0.990765
KOTAKBANK       0.001169   0.031571  0.990171
MARUTI          0.001136   0.022223  0.988932
VEDL            0.001106   0.035820  0.990763
BAJAJFINSV      0.001045   0.028595  0.984692
ICICIBANK       0.000947   0.029996  0.990765
ADANIPORTS      0.000883   0.036699  0.985250
HDFC            0.000853   0.026113  0.990765
BHARTIARTL      0.000850   0.025191  0.989527
ASIANPAINT      0.000815   0.022366  0.990765
HDFCBANK        0.000804   0.023992  0.990765
HCLTECH         0.000798   0.039872  0.990755
TECHM           0.000784   0.029271  0.986520
NESTLEIND       0.000783   0.015259  0.982537
TATASTEEL       0.000766   0.027853  0.990765
RELIANCE        0.000722   0.024056  0.990765
POWERGRID       0.000687   0.024699  0.985412
TCS             0.000643   0.023875  0.988161
TATAMOTORS      0.000641   0.030760  0.990765
GRASIM          0.000635   0.024941  0.990765
SBIN            0.000629   0.026861  0.990765
BRITANNIA       0.000612   0.021170  0.990763
BAJAJ-AUTO      0.000604   0.024783  0.984697
HEROMOTOCO      0.000556   0.024463  0.990765
DRREDDY         0.000543   0.023270  0.990765
MM              0.000536   0.027856  0.990765
BPCL            0.000497   0.029495  0.990765
HINDALCO        0.000473   0.029663  0.990765
GAIL            0.000469   0.025371  0.990171
HINDUNILVR      0.000454   0.022558  0.990765
SUNPHARMA       0.000414   0.029141  0.990765
CIPLA           0.000340   0.024405  0.990765
ITC             0.000337   0.024668  0.990765
NTPC            0.000309   0.019321  0.988014
ONGC            0.000300   0.026256  0.990765
WIPRO           0.000233   0.030627  0.990765
ZEEL            0.000231   0.033140  0.990765
IOC             0.000202   0.026531  0.990765
INFY            0.000134   0.030059  0.990765
COALINDIA      -0.000034   0.020346  0.981139

In [22]:
df_new.rename(columns={
    "('daily_return',     'mean')": "avg_return",
    "(  'volatility',     'mean')": "avg_volatility",
    "(       'trend', '<lambda>')":"%upward_trend"}, inplace=True)
df_new

In [23]:
df_new.columns = ['_'.join(col) for col in df_new.columns]

In [29]:
df_new.columns

Index(['avg_return', 'avg_volatility', '%upward_trend'], dtype='object')

In [27]:
df_new=df_new.drop(columns='avg_return_')

In [30]:
df_new.sort_values(by='avg_return',ascending=False)

             avg_return  avg_volatility  %upward_trend
Firm
LT             0.076309        4.900433       0.988289
UPL            0.013274        0.831078       0.988570
JSWSTEEL       0.010461        0.602408       0.987732
ULTRACEMCO     0.007031        0.389403       0.988164
NIFTY50_all    0.002566        0.670331       0.999579
BAJFINANCE     0.001562        0.030670       0.990640
SHREECEM       0.001546        0.024554       0.990171
INDUSINDBK     0.001342        0.031018       0.990171
EICHERMOT      0.001322        0.030669       0.990756
TITAN          0.001220        0.031508       0.990765
AXISBANK       0.001193        0.030558       0.990765
KOTAKBANK      0.001169        0.031571       0.990171
MARUTI         0.001136        0.022223       0.988932
VEDL           0.001106        0.035820       0.990763
BAJAJFINSV     0.001045        0.028595       0.984692
ICICIBANK      0.000947        0.029996       0.990765
ADANIPORTS     0.000883        0.036699       0.985250
HDFC           0.000853        0.026113       0.990765
BHARTIARTL     0.000850        0.025191       0.989527
ASIANPAINT     0.000815        0.022366       0.990765
HDFCBANK       0.000804        0.023992       0.990765
HCLTECH        0.000798        0.039872       0.990755
TECHM          0.000784        0.029271       0.986520
NESTLEIND      0.000783        0.015259       0.982537
TATASTEEL      0.000766        0.027853       0.990765
RELIANCE       0.000722        0.024056       0.990765
POWERGRID      0.000687        0.024699       0.985412
TCS            0.000643        0.023875       0.988161
TATAMOTORS     0.000641        0.030760       0.990765
GRASIM         0.000635        0.024941       0.990765
SBIN           0.000629        0.026861       0.990765
BRITANNIA      0.000612        0.021170       0.990763
BAJAJ-AUTO     0.000604        0.024783       0.984697
HEROMOTOCO     0.000556        0.024463       0.990765
DRREDDY        0.000543        0.023270       0.990765
MM             0.000536        0.027856       0.990765
BPCL           0.000497        0.029495       0.990765
HINDALCO       0.000473        0.029663       0.990765
GAIL           0.000469        0.025371       0.990171
HINDUNILVR     0.000454        0.022558       0.990765
SUNPHARMA      0.000414        0.029141       0.990765
CIPLA          0.000340        0.024405       0.990765
ITC            0.000337        0.024668       0.990765
NTPC           0.000309        0.019321       0.988014
ONGC           0.000300        0.026256       0.990765
WIPRO          0.000233        0.030627       0.990765
ZEEL           0.000231        0.033140       0.990765
IOC            0.000202        0.026531       0.990765
INFY           0.000134        0.030059       0.990765
COALINDIA     -0.000034        0.020346       0.981139

In [33]:
df_new['return_score'] = ((df_new['avg_return'] - df_new['avg_return'].min()) / (df_new['avg_return'].max() - df_new['avg_return'].min()))*0.5
df_new['volatility_score'] =(1-((df_new['avg_volatility'] - df_new['avg_volatility'].min()) / (df_new['avg_volatility'].max() - df_new['avg_volatility'].min())))*0.3
df_new['trend_score'] = ((df_new['%upward_trend'] - df_new['%upward_trend'].min()) / (df_new['%upward_trend'].max() - df_new['%upward_trend'].min()))*0.2
df_new['investment_score']=df_new['return_score']+df_new['volatility_score']+df_new['trend_score']
df_new

,Firm,avg_return,avg_volatility,%upward_trend,return_score,volatility_score,trend_score,investment_score
0,ADANIPORTS,0.000883,0.036699,0.985250,0.006009,0.298683,0.044583,0.349275
1,ASIANPAINT,0.000815,0.022366,0.990765,0.005562,0.299564,0.104403,0.409528
2,AXISBANK,0.001193,0.030558,0.990765,0.008034,0.299060,0.104403,0.411498
3,BAJAJ-AUTO,0.000604,0.024783,0.984697,0.004183,0.299415,0.038588,0.342186
4,BAJAJFINSV,0.001045,0.028595,0.984692,0.007070,0.299181,0.038536,0.344786
5,BAJFINANCE,0.001562,0.030670,0.990640,0.010457,0.299054,0.103045,0.412555
6,BHARTIARTL,0.000850,0.025191,0.989527,0.005792,0.299390,0.090969,0.396152
7,BPCL,0.000497,0.029495,0.990765,0.003479,0.299126,0.104403,0.407007
8,BRITANNIA,0.000612,0.021170,0.990763,0.004234,0.299637,0.104384,0.408255
9,CIPLA,0.000340,0.024405,0.990765,0.002448,0.299438,0.104403,0.406289
10,COALINDIA,-0.000034,0.020346,0.981139,0.000000,0.299688,0.000000,0.299688
11,DRREDDY,0.000543,0.023270,0.990765,0.003782,0.299508,0.104403,0.407694
12,EICHERMOT,0.001322,0.030669,0.990756,0.008883,0.299054,0.104309,0.412246
13,GAIL,0.000469,0.025371,0.990171,0.003293,0.299379,0.097953,0.400625
14,GRASIM,0.000635,0.024941,0.990765,0.004383,0.299405,0.104403,0.408191
15,HCLTECH,0.000798,0.039872,0.990755,0.005449,0.298489,0.104290,0.408227
16,HDFC,0.000853,0.026113,0.990765,0.005811,0.299333,0.104403,0.409548
17,HDFCBANK,0.000804,0.023992,0.990765,0.005493,0.299464,0.104403,0.409360
18,HEROMOTOCO,0.000556,0.024463,0.990765,0.003867,0.299435,0.104403,0.407705
19,HINDALCO,0.000473,0.029663,0.990765,0.003322,0.299115,0.104403,0.406840
20,HINDUNILVR,0.000454,0.022558,0.990765,0.003201,0.299552,0.104403,0.407155
21,ICICIBANK,0.000947,0.029996,0.990765,0.006425,0.299095,0.104403,0.409923
22,INDUSINDBK,0.001342,0.031018,0.990171,0.009011,0.299032,0.097953,0.405996
23,INFY,0.000134,0.030059,0.990765,0.001104,0.299091,0.104403,0.404598
24,IOC,0.000202,0.026531,0.990765,0.001547,0.299308,0.104403,0.405258
25,ITC,0.000337,0.024668,0.990765,0.002432,0.299422,0.104403,0.406257
26,JSWSTEEL,0.010461,0.602408,0.987732,0.068739,0.263943,0.071501,0.404182
27,KOTAKBANK,0.001169,0.031571,0.990171,0.007878,0.298998,0.097953,0.404830
28,LT,0.076309,4.900433,0.988289,0.500000,0.000000,0.077543,0.577543
29,MARUTI,0.001136,0.022223,0.988932,0.007664,0.299572,0.084516,0.391752
30,MM,0.000536,0.027856,0.990765,0.003733,0.299226,0.104403,0.407363
31,NESTLEIND,0.000783,0.015259,0.982537,0.005350,0.300000,0.015164,0.320514
32,NIFTY50_all,0.002566,0.670331,0.999579,0.017029,0.259772,0.200000,0.476801
33,NTPC,0.000309,0.019321,0.988014,0.002248,0.299751,0.074560,0.376559
34,ONGC,0.000300,0.026256,0.990765,0.002186,0.299325,0.104403,0.405914
35,POWERGRID,0.000687,0.024699,0.985412,0.004722,0.299420,0.046345,0.350487
36,RELIANCE,0.000722,0.024056,0.990765,0.004954,0.299460,0.104403,0.408817
37,SBIN,0.000629,0.026861,0.990765,0.004342,0.299288,0.104403,0.408032
38,SHREECEM,0.001546,0.024554,0.990171,0.010350,0.299429,0.097953,0.407732
39,SUNPHARMA,0.000414,0.029141,0.990765,0.002937,0.299148,0.104403,0.406488
40,TATAMOTORS,0.000641,0.030760,0.990765,0.004423,0.299048,0.104403,0.407874
41,TATASTEEL,0.000766,0.027853,0.990765,0.005243,0.299227,0.104403,0.408873
42,TCS,0.000643,0.023875,0.988161,0.004435,0.299471,0.076162,0.380068
43,TECHM,0.000784,0.029271,0.986520,0.005356,0.299140,0.058359,0.362855
44,TITAN,0.001220,0.031508,0.990765,0.008215,0.299002,0.104403,0.411621
45,ULTRACEMCO,0.007031,0.389403,0.988164,0.046274,0.277024,0.076193,0.399491
46,UPL,0.013274,0.831078,0.988570,0.087162,0.249900,0.080595,0.417658
47,VEDL,0.001106,0.035820,0.990763,0.007470,0.298737,0.104384,0.410592
48,WIPRO,0.000233,0.030627,0.990765,0.001749,0.299056,0.104403,0.405208
49,ZEEL,0.000231,0.033140,0.990765,0.001738,0.298902,0.104403,0.405043

In [32]:
df_new=df_new.reset_index(col_fill='Firm')

In [35]:
df_new.to_excel('Metadata_new.xlsx',index=False)
df_new

,Firm,avg_return,avg_volatility,%upward_trend,return_score,volatility_score,trend_score,investment_score
0,ADANIPORTS,0.000883,0.036699,0.985250,0.006009,0.298683,0.044583,0.349275
1,ASIANPAINT,0.000815,0.022366,0.990765,0.005562,0.299564,0.104403,0.409528
2,AXISBANK,0.001193,0.030558,0.990765,0.008034,0.299060,0.104403,0.411498
3,BAJAJ-AUTO,0.000604,0.024783,0.984697,0.004183,0.299415,0.038588,0.342186
4,BAJAJFINSV,0.001045,0.028595,0.984692,0.007070,0.299181,0.038536,0.344786
5,BAJFINANCE,0.001562,0.030670,0.990640,0.010457,0.299054,0.103045,0.412555
6,BHARTIARTL,0.000850,0.025191,0.989527,0.005792,0.299390,0.090969,0.396152
7,BPCL,0.000497,0.029495,0.990765,0.003479,0.299126,0.104403,0.407007
8,BRITANNIA,0.000612,0.021170,0.990763,0.004234,0.299637,0.104384,0.408255
9,CIPLA,0.000340,0.024405,0.990765,0.002448,0.299438,0.104403,0.406289
10,COALINDIA,-0.000034,0.020346,0.981139,0.000000,0.299688,0.000000,0.299688
11,DRREDDY,0.000543,0.023270,0.990765,0.003782,0.299508,0.104403,0.407694
12,EICHERMOT,0.001322,0.030669,0.990756,0.008883,0.299054,0.104309,0.412246
13,GAIL,0.000469,0.025371,0.990171,0.003293,0.299379,0.097953,0.400625
14,GRASIM,0.000635,0.024941,0.990765,0.004383,0.299405,0.104403,0.408191
15,HCLTECH,0.000798,0.039872,0.990755,0.005449,0.298489,0.104290,0.408227
16,HDFC,0.000853,0.026113,0.990765,0.005811,0.299333,0.104403,0.409548
17,HDFCBANK,0.000804,0.023992,0.990765,0.005493,0.299464,0.104403,0.409360
18,HEROMOTOCO,0.000556,0.024463,0.990765,0.003867,0.299435,0.104403,0.407705
19,HINDALCO,0.000473,0.029663,0.990765,0.003322,0.299115,0.104403,0.406840
20,HINDUNILVR,0.000454,0.022558,0.990765,0.003201,0.299552,0.104403,0.407155
21,ICICIBANK,0.000947,0.029996,0.990765,0.006425,0.299095,0.104403,0.409923
22,INDUSINDBK,0.001342,0.031018,0.990171,0.009011,0.299032,0.097953,0.405996
23,INFY,0.000134,0.030059,0.990765,0.001104,0.299091,0.104403,0.404598
24,IOC,0.000202,0.026531,0.990765,0.001547,0.299308,0.104403,0.405258
25,ITC,0.000337,0.024668,0.990765,0.002432,0.299422,0.104403,0.406257
26,JSWSTEEL,0.010461,0.602408,0.987732,0.068739,0.263943,0.071501,0.404182
27,KOTAKBANK,0.001169,0.031571,0.990171,0.007878,0.298998,0.097953,0.404830
28,LT,0.076309,4.900433,0.988289,0.500000,0.000000,0.077543,0.577543
29,MARUTI,0.001136,0.022223,0.988932,0.007664,0.299572,0.084516,0.391752
30,MM,0.000536,0.027856,0.990765,0.003733,0.299226,0.104403,0.407363
31,NESTLEIND,0.000783,0.015259,0.982537,0.005350,0.300000,0.015164,0.320514
32,NIFTY50_all,0.002566,0.670331,0.999579,0.017029,0.259772,0.200000,0.476801
33,NTPC,0.000309,0.019321,0.988014,0.002248,0.299751,0.074560,0.376559
34,ONGC,0.000300,0.026256,0.990765,0.002186,0.299325,0.104403,0.405914
35,POWERGRID,0.000687,0.024699,0.985412,0.004722,0.299420,0.046345,0.350487
36,RELIANCE,0.000722,0.024056,0.990765,0.004954,0.299460,0.104403,0.408817
37,SBIN,0.000629,0.026861,0.990765,0.004342,0.299288,0.104403,0.408032
38,SHREECEM,0.001546,0.024554,0.990171,0.010350,0.299429,0.097953,0.407732
39,SUNPHARMA,0.000414,0.029141,0.990765,0.002937,0.299148,0.104403,0.406488
40,TATAMOTORS,0.000641,0.030760,0.990765,0.004423,0.299048,0.104403,0.407874
41,TATASTEEL,0.000766,0.027853,0.990765,0.005243,0.299227,0.104403,0.408873
42,TCS,0.000643,0.023875,0.988161,0.004435,0.299471,0.076162,0.380068
43,TECHM,0.000784,0.029271,0.986520,0.005356,0.299140,0.058359,0.362855
44,TITAN,0.001220,0.031508,0.990765,0.008215,0.299002,0.104403,0.411621
45,ULTRACEMCO,0.007031,0.389403,0.988164,0.046274,0.277024,0.076193,0.399491
46,UPL,0.013274,0.831078,0.988570,0.087162,0.249900,0.080595,0.417658
47,VEDL,0.001106,0.035820,0.990763,0.007470,0.298737,0.104384,0.410592
48,WIPRO,0.000233,0.030627,0.990765,0.001749,0.299056,0.104403,0.405208
49,ZEEL,0.000231,0.033140,0.990765,0.001738,0.298902,0.104403,0.405043